In [1]:
import pandas as pd
from pathlib import Path
import os

In [2]:
dataset_path = Path("~/mnt/shared-resources-sentient-research/salah_resources/datasets/officeqa/")
data_file = "officeqa.csv"
data = pd.read_csv(os.path.join(dataset_path, data_file))

In [4]:
data.head()

,uid,question,answer,source_docs,source_files,difficulty
0,UID0001,What were the total expenditures (in millions ...,"2,602",https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt,hard
1,UID0002,What were the total expenditures of the U.S fe...,507,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1944_01.txt,easy
2,UID0003,Using specifically only the reported values fo...,"44,463",https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1954_02.txt,hard
3,UID0004,Using specifically only the reported values fo...,1608.80%,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt\r\ntreasury_bull...,hard
4,UID0005,Using specifically only the reported values fo...,39482.03,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt\r\ntreasury_bull...,hard

In [5]:
old_data = pd.read_csv("~/Desktop/officeqa.csv")

In [6]:
old_data.head()

,uid,question,answer,source_docs,source_files,difficulty,pseudo_labels
0,UID0001,What were the total expenditures (in millions ...,"2,602",https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt,hard,Lookup/Extraction
1,UID0002,What were the total expenditures of the U.S fe...,507,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1944_01.txt,easy,Lookup/Extraction
2,UID0003,Using specifically only the reported values fo...,"44,463",https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1954_02.txt,hard,Aggregation
3,UID0004,Using specifically only the reported values fo...,1608.80%,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt\ntreasury_bullet...,hard,Comparison/Change
4,UID0005,Using specifically only the reported values fo...,39482.03,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt\ntreasury_bullet...,hard,Transform/Normalize

In [7]:
data = data.merge(
    old_data[['question', 'pseudo_labels']], 
    on='question', 
    how='left'
)

In [10]:
data.to_csv("~/Desktop/officeqa.csv", index=False)